### ISSUE TITLE
Integrating with istio helm chart installs

### ISSUE THREAD

**Issue by sepulworld** [cert-manager/istio-csr#113]
Does anyone have any example values inputs when integrating istio-csr with an istio operator setup using Helm https://istio.io/latest/docs/setup/install/helm/

I see istio-csr refers to this https://github.com/cert-manager/istio-csr/blob/main/hack/istio-config-1.10.0.yaml but does anyone have a translation of this to the istio/istiod helm chart install?

**Comment by keithmattix** [comment]
Bumping this: IstioOperator is now [discouraged](https://istio.io/latest/docs/setup/install/operator/). It would be great to have some instructions for how to set this up with native Helm

**Comment by ajp-lsq** [comment]
Third bump, trying to figure this out right now.

In case anyone else is working on this, what I've found so far is `.global.mountMtlsCerts` in the istio/istiod helm chart (version 1.13.0 at least). Looks like this affects `files/gen-istio.yaml` in the istiod helm chart, mounting volumes and volume mounts as such:

```yaml
          {{- if .Values.global.mountMtlsCerts }}
          # Use the key and cert mounted to /etc/certs/ for the in-cluster mTLS communications.
          - name: istio-certs
            secret:
              optional: true
              {{ if eq .Spec.ServiceAccountName "" }}
              secretName: istio.default
              {{ else -}}
              secretName: {{  printf "istio.%s" .Spec.ServiceAccountName }}
              {{  end -}}
          {{- end }}
```

```yaml
            {{- if .Values.global.mountMtlsCerts }}
            # Use the key and cert mounted to /etc/certs/ for the in-cluster mTLS communications.
            - mountPath: /etc/certs/
              name: istio-certs
              readOnly: true
            {{- end }}
```

It does the same thing in `files/gateway-injection-template.yaml` and `files/injection-template.yaml`.

I'm not sure which secret this is in relation to the changes in the IstioOperator resource. It doesn't really look like it applies to either? Unfortunately, it doesn't seem the chart allows for definition of arbitrary extra volumes either.

Other than that `caAddress` and `trustDomain` can both be changed by the chart, and you can define custom envs to set ENABLE_CA_SERVER to false.

**Comment by sepulworld** [comment]
@ajp-lsq can you ping us here when you have PR on upstream chart or reference this issue in PR? Thanks for the help!

**Comment by ceastman-r7** [comment]
@ajp-lsq I am also interested in this work. Thank you.

**Comment by tabnul** [comment]
> ajp-lsq

Did you allready PR your changes to the upstream project?
Thanks!

**Comment by cm3brian** [comment]
I'm kinda confused here, as a person moving from istio-operator to istio helm, it seems that this "issue" was handled some time ago with a "zero config" solution here: https://github.com/istio/istio/pull/39375

Can someone explain if/why this does not work? as I would think the "zero-config" route makes sense with just leveraging known paths mounts for secrets?

I'll be progressing into testing in the near future so I'll also report back my own findings here.

**Comment by volodymyr-mykhailyk** [comment]
> I'm kinda confused here, as a person moving from istio-operator to istio helm, it seems that this "issue" was handled some time ago with a "zero config" solution here: [istio/istio#39375](https://github.com/istio/istio/pull/39375)
> 
> Can someone explain if/why this does not work? as I would think the "zero-config" route makes sense with just leveraging known paths mounts for secrets?
> 
> I'll be progressing into testing in the near future so I'll also report back my own findings here.

Just deployed istio in staging with the "zero config" - and it simply works. 
In my deployment, there are:
- custom Issuer named `istio-ca` in `istio-system` namespace that can generate certificate using vault
- no special configuration for `istio-csr` helm
- istio helm chart has CA server disabled and caAddress set to `istio-csr` module:
  ```yaml
  global:
    caAddress: cert-manager-istio-csr.cert-manager.svc:443
  pilot:
    env:
      ENABLE_CA_SERVER: false
  ```

So I suspect there have been two initiatives in parallel to solve this problem from different ends. One that you mentioned https://github.com/istio/istio/pull/39375 and one https://github.com/istio/istio/pull/45517 that @tomreeb has contributed to the istio recently. 

Now someone just needs to update the documentation so one or both are easier to use
