### ISSUE TITLE
Metrics scraped twice

### ISSUE THREAD

**Issue by konnoska** [cert-manager/istio-csr#180]
Setting the following values:

```
app:
  metrics:
    service:
      enabled: true
      servicemonitor:
        enabled: true
```
Creates a servicemonitor that targets both `<istio-csr-servicename>-metrics` and `<istio-csr-servicename>` resulting in pod metrics being scraped twice.
