### ISSUE TITLE
Modify schema validation for additional property domain

### ISSUE THREAD

**Issue by volvera10** [cert-manager/istio-csr#324]
The latest helm chart for istio-csr v0.9.0 results in the following schema error:
```
Helm install failed for release cert-manager/csr with chart cert-manager-istio-csr@v0.9.0: values don't meet the specifications of the schema(s) in the following chart(s):
      cert-manager-istio-csr:
      - (root): Additional property domain is not allowed
```
Please allow for `domain` property or additional properties in the schema validation.
values.yml example use-case:
```
values:
      domain: {{ domainName }}
      app:
        certmanager:
          namespace: istio-system
          issuer:
            name: vault-issuer
            kind: Issuer
            group: cert-manager.io
        tls:
          trustDomain: "cluster.local"
          istiodCertificateEnable: true
          rootCAFile: /var/run/secrets/istio-csr/ca.cert.pem
          certificateDNSNames:
            - cert-manager-istio-csr.cert-manager.svc
          certificateDuration: 24h
          istiodCertificateDuration: 24h
          istiodCertificateRenewBefore: 30m
          istiodCertificateEnable: true
          istiodPrivateKeySize: 2048
```
This error does not occur in v0.8.1 as there was no schema validation check in that release or at least `values.schema.json` did not exist in the helm chart.
