### ISSUE TITLE
Wrong dnsNames in Certificate when app.tls.istiodCertificateEnable=dynamic

### ISSUE THREAD

**Issue by Jinn22** [cert-manager/istio-csr#432]
in istio-csr v0.11.0 and v0.12.0, when app.tls.istiodCertificateEnable=dynamic and app.istio.revisions=[1-22-1]. The certificate contains wrong dnsNames: 
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istiod-dynamic
spec:
  commonName: istiod.istio-system.svc
  dnsNames:
  - istiod1-22-1.istio-system.svc
...
```
dnsName should be **istiod-1-22-1.istio-system.svc**
