### ISSUE TITLE
commonName required for AWS PCA

### ISSUE THREAD

**Issue by bpotaczek** [cert-manager/istio-csr#83]
AWS PCA expects the commonName to be passed in as part of the CSR. Adding `commonName: istiod.istio-system.svc` in the Certificate.yaml file was all that was needed.

```
spec:
  dnsNames:
  - istiod.istio-system.svc
  uris:
    - spiffe://cluster.local/ns/istio-system/sa/istiod-service-account
  secretName: istiod-tls
  commonName: istiod.istio-system.svc
...
```

**Comment by JoshVanL** [comment]
Thanks @bpotaczek! It is surprising to me that this works as the istio workloads themselves using the same Issuer don't have a CommonName set IIRC.

**Comment by assafmanzur** [comment]
@bpotaczek Can help? I'm getting `api error ValidationException: 1 validation error detected: Value '0' at 'validity.value' failed to satisfy constraint: Member must have value greater than or equal to 1` when using `AWSPCAClusterIssuer` as issuer. the cert manager works fine outside the istio-csr 

can you please upload the certificate.yaml and is there any custom values except those? 

```
   issuer:
      # -- Issuer name set on created CertificateRequests for both istio-csr's
      # serving certificate and incoming gRPC CSRs.
      name: private-root-ca
      # -- Issuer kind set on created CertificateRequests for both istio-csr's
      # serving certificate and incoming gRPC CSRs.
      kind: AWSPCAClusterIssuer
      # -- Issuer group name set on created CertificateRequests for both
      # istio-csr's serving certificate and incoming gRPC CSRs.
      group: awspca.cert-manager.io
```

Thanks
